options:
  docker: true
  size: 2x
pipelines:
  branches:
    develop:
      - step:
          image: google/cloud-sdk:latest
          name: Deploy to develop
          deployment: develop
          caches:
            - docker
          services:
           - docker
          options:
            size: 2x
          script:
            - echo "AUDIO_FILE_SIZE_LIMIT=$ENV_AUDIO_FILE_SIZE_LIMIT" > .env
            - echo "VIDEO_FILE_SIZE_LIMIT=$ENV_VIDEO_FILE_SIZE_LIMIT" >> .env
            - echo "IMAGE_FILE_SIZE_LIMIT=$ENV_IMAGE_FILE_SIZE_LIMIT" >> .env
            - echo "GCLOUD_PROJECT=$ENV_GCLOUD_PROJECT" >> .env
            - echo "GOOGLE_CLOUD_LOCATION_ID=$ENV_GOOGLE_CLOUD_LOCATION_ID" >> .env
            - echo "GOOGLE_CLOUD_PROJECT_ID=$ENV_GOOGLE_CLOUD_PROJECT_ID" >> .env
            - echo "GOOGLE_CLOUD_STORAGE_BUCKET_NAME=$ENV_GOOGLE_CLOUD_STORAGE_BUCKET_NAME" >> .env
            - echo "GOOGLE_SERVICE_ACCOUNT_KEY_LOCATION=$ENV_GOOGLE_SERVICE_ACCOUNT_KEY_LOCATION" >> .env
            - echo "GOOGLE_TRANSLATE_API_KEY=$ENV_GOOGLE_TRANSLATE_API_KEY" >> .env
            - echo "GOOGLE_PLACES_API_KEY=$ENV_GOOGLE_PLACES_API_KEY" >> .env
            - echo "SENDER_EMAIL_ADDRESS=$ENV_SENDER_EMAIL_ADDRESS" >> .env
            - echo "API_BASE_URL=$ENV_API_BASE_URL" >> .env
            - echo "SUPER_ADMIN_EMAIL=$ENV_SUPER_ADMIN_EMAIL" >> .env
            - echo "DOCS_PASSWORD=$ENV_DOCS_PASSWORD" >> .env
            - echo "DOCS_USER=$ENV_DOCS_USER" >> .env
            - echo "REFRESH_TOKEN_EXPIRES_IN=$ENV_REFRESH_TOKEN_EXPIRES_IN" >> .env
            - echo "ACCESS_TOKEN_EXPIRES_IN=$ENV_ACCESS_TOKEN_EXPIRES_IN" >> .env
            - echo "REFRESH_TOKEN_PRIVATE_KEY=$ENV_REFRESH_TOKEN_PRIVATE_KEY" >> .env
            - echo "ACCESS_TOKEN_PRIVATE_KEY=$ENV_ACCESS_TOKEN_PRIVATE_KEY" >> .env
            - echo "ACCESS_TOKEN_PUBLIC_KEY=$ENV_ACCESS_TOKEN_PUBLIC_KEY" >> .env
            - echo "REFRESH_TOKEN_PUBLIC_KEY=$ENV_REFRESH_TOKEN_PUBLIC_KEY" >> .env
            - echo "PASSWORD_BASE64_REGEX=$ENV_PASSWORD_BASE64_REGEX" >> .env
            - echo "SALT_ROUNDS=$ENV_SALT_ROUNDS" >> .env
            - echo "TYPEORM_RUN_MIGRATIONS=$ENV_TYPEORM_RUN_MIGRATIONS" >> .env
            - echo "TYPEORM_SYNCHRONIZE=$ENV_TYPEORM_SYNCHRONIZE" >> .env
            - echo "SENDGRID_API_KEY=$ENV_SENDGRID_API_KEY" >> .env
            - echo "DB_NAME=$ENV_DB_NAME" >> .env
            - echo "DB_PASSWORD=$ENV_DB_PASSWORD" >> .env
            - echo "DB_USERNAME=$ENV_DB_USERNAME" >> .env
            - echo "DB_PORT=$ENV_DB_PORT" >> .env
            - echo "DB_HOSTNAME=$ENV_DB_HOSTNAME" >> .env
            - echo "DB_POOL_SIZE=$ENV_DB_POOL_SIZE" >> .env
            - echo "_DB_NAME=$_DB_NAME" >> .env
            - echo "LOG_REQUESTS=$ENV_LOG_REQUESTS" >> .env
            - echo "LOG_TO_CONSOLE=$ENV_LOG_TO_CONSOLE" >> .env
            - echo "LOGIN_LIMITER_BLOCKING_DURATION_IN_SECONDS=$ENV_LOGIN_LIMITER_BLOCKING_DURATION_IN_SECONDS" >> .env
            - echo "LOGIN_LIMITER_DURATION_IN_SECONDS=$ENV_LOGIN_LIMITER_DURATION_IN_SECONDS" >> .env
            - echo "LOGIN_LIMITER_POINTS=$ENV_LOGIN_LIMITER_POINTS" >> .env
            - echo "RATE_LIMITER_DURATION_IN_SECONDS=$ENV_RATE_LIMITER_DURATION_IN_SECONDS" >> .env
            - echo "RATE_LIMITER_POINTS=$ENV_RATE_LIMITER_POINTS" >> .env
            - echo "NODE_ENV=$ENV_NODE_ENV" >> .env
            - echo "BASE_URL=$ENV_BASE_URL" >> .env
            - echo "PORT=$ENV_PORT" >> .env
            - echo "_SERVICE_NAME=$_SERVICE_NAME" >> .env
            - echo "SUPER_ADMIN_PASSWORD=$SUPER_ADMIN_PASSWORD" >> .env
            - echo "SUPER_ADMIN_EMAIL=$SUPER_ADMIN_EMAIL" >> .env
            - echo "USE_UNIX_SOCKET=$ENV_USE_UNIX_SOCKET" >> .env
            - echo "DEFAULT_CASE_PASSWORD=$ENV_DEFAULT_CASE_PASSWORD" >> .env


            # SETUP
            - export IMAGE_NAME=$CLOUD_RUN_REGION-docker.pkg.dev/$ENV_GOOGLE_CLOUD_PROJECT_ID/$GCP_AR_REPOSITORY/$_SERVICE_NAME/$BITBUCKET_REPO_SLUG:$BITBUCKET_COMMIT
            - export ENVIRONMENT=production
            - echo $GCP_SA_KEY | base64 -d > ~/.gcloud-api-key.json
            - gcloud auth activate-service-account --key-file ~/.gcloud-api-key.json
            - gcloud config set project $ENV_GOOGLE_CLOUD_PROJECT_ID
            - gcloud auth configure-docker $CLOUD_RUN_REGION-docker.pkg.dev

            # BUILD AND PUSH THE IMAGE
            - export DOCKER_BUILDKIT=0
            - docker build -t $IMAGE_NAME .
            - docker push $IMAGE_NAME

            # DEPLOYMENT
            - gcloud run deploy $_SERVICE_NAME --image $IMAGE_NAME --region $CLOUD_RUN_REGION --platform managed --max-instances 4 --min-instances 1 --port $ENV_PORT --cpu-boost --cpu-throttling --add-cloudsql-instances $DB_INSTANCE --session-affinity --labels managed-by=bitbucket-pipeline-cloud-run,commit-sha=$BITBUCKET_COMMIT,bitbucket-build-number=$BITBUCKET_BUILD_NUMBER --memory 4Gi --quiet


definitions:
  services:
    docker:
      memory: 4096
